apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ovwk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ovwk
    app.kubernetes.io/part-of: ci1t-830-0052-app
  name: devfile-sample-ovwk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ovwk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ovwk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0052-tenant/ci1t-830-0052-app/devfile-sample-ovwk@sha256:00a289bfeac295b3ea80b9044ee9771acad79d779e2851f29108fd901e156793
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
